// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDWorkloadProfilesProfileQidRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Workload profile ID.
	//
	//
	ProfileQid string `pathParam:"style=simple,explode=false,name=profileQid"`
}

type DeleteOrgsOrgIDWorkloadProfilesProfileQidResponse struct {
	ContentType string
	// The Workload Profile is not found or is not accessible by the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
