// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrgsOrgIDAppsAppIDWebhooksJobIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Webhook ID.
	//
	//
	JobID string `pathParam:"style=simple,explode=false,name=jobId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type DeleteOrgsOrgIDAppsAppIDWebhooksJobIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
