// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDEnvTypesEnvTypeIDRequest struct {
	// ID of the Environment Type.
	//
	//
	EnvTypeID string `pathParam:"style=simple,explode=false,name=envTypeId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type DeleteOrgsOrgIDEnvTypesEnvTypeIDResponse struct {
	ContentType string
	// The Environment Type requested.
	//
	//
	EnvironmentTypeResponse *shared.EnvironmentTypeResponse
	// The Authorization header was not present or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// There are 1 or more Environments with this Type.
	//
	// To delete an Environment Type, there can be no Environments with that type in the Organization.
	DeleteOrgsOrgIDEnvTypesEnvTypeID409ApplicationJSONObjects []map[string]string
}
