// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDRegistriesRegIDRequest struct {
	// Unique (alpha-numerical) organization identifier.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// Unique (alpha-numerical) registry identifier.
	//
	//
	RegID string `pathParam:"style=simple,explode=false,name=regId"`
}

type DeleteOrgsOrgIDRegistriesRegIDResponse struct {
	ContentType string
	// Request parameters are incomplete or invalid.
	//
	//
	ErrorInfoResponse *shared.ErrorInfoResponse
	StatusCode        int
	RawResponse       *http.Response
}
