// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDResourcesDefsDefIDRequest struct {
	// The Resource Definition ID.
	//
	//
	DefID string `pathParam:"style=simple,explode=false,name=defId"`
	// If set to `true`, will mark the Resource Definition for deletion, even if it affects existing Active Resources.
	//
	//
	Force *bool `queryParam:"style=form,explode=true,name=force"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type DeleteOrgsOrgIDResourcesDefsDefIDResponse struct {
	ContentType string
	// A Resource Driver with the 'driverId' ID is not found or is not accessible by the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// List of Active Resources that still reference this Resource Definition.
	//
	//
	ResourceDefinitionChangeResponses []shared.ResourceDefinitionChangeResponse
	StatusCode                        int
	RawResponse                       *http.Response
}
