// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrgsOrgIDAppsAppIDEnvsEnvIDResourcesTypeResIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Resource ID.
	//
	//
	ResID string `pathParam:"style=simple,explode=false,name=resId"`
	// The Resource Type.
	//
	//
	Type string `pathParam:"style=simple,explode=false,name=type"`
}

type DeleteOrgsOrgIDAppsAppIDEnvsEnvIDResourcesTypeResIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
