// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrgsOrgIDAppsAppIDEnvsEnvIDRulesRuleIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Automation Rule ID.
	//
	//
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

type DeleteOrgsOrgIDAppsAppIDEnvsEnvIDRulesRuleIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
