// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDWorkloadProfilesProfileIDVersionsVersionRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Workload profile ID.
	//
	//
	ProfileID string `pathParam:"style=simple,explode=false,name=profileId"`
	// The Version.
	//
	//
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

type DeleteOrgsOrgIDWorkloadProfilesProfileIDVersionsVersionResponse struct {
	ContentType string
	// The Workload Profile Version is not found or is not accessible by the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
