// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDResourcesDriversDriverIDRequest struct {
	// The Resources Driver ID to delete.
	//
	//
	DriverID string `pathParam:"style=simple,explode=false,name=driverId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type DeleteOrgsOrgIDResourcesDriversDriverIDResponse struct {
	ContentType string
	// Internal application error.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
