// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type DeleteOrgsOrgIDArtefactsArtefactIDRequest struct {
	// The Artefact ID.
	//
	//
	ArtefactID string `pathParam:"style=simple,explode=false,name=artefactId"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type DeleteOrgsOrgIDArtefactsArtefactIDResponse struct {
	ContentType string
	// Request forbidden. This action can only be performed by users holding the Administrator role. It is not possible to delete a built-in artefact.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
