// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetCurrentUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The extended user profile of the user.
	//
	//
	UserProfileExtendedResponse *shared.UserProfileExtendedResponse
}
