// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDWorkloadProfilesProfileQidVersionsRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Workload profile qualified ID.
	//
	//
	ProfileQid string `pathParam:"style=simple,explode=false,name=profileQid"`
	// Optional query parameter, defines version constraint pattern (https://github.com/Masterminds/semver#checking-version-constraints).
	//
	//
	Version *string `queryParam:"style=form,explode=true,name=version"`
}

type GetOrgsOrgIDWorkloadProfilesProfileQidVersionsResponse struct {
	ContentType string
	// Workload Profile Versions not found or not accessible by the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// A possibly empty list of Workload Profile Versions.
	//
	//
	WorkloadProfileVersionResponses []shared.WorkloadProfileVersionResponse
}
