// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDEventsRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDEventsResponse struct {
	ContentType string
	// A list of Events.
	//
	//
	EventResponses []shared.EventResponse
	StatusCode     int
	RawResponse    *http.Response
}
