// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDWorkloadProfilesRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDWorkloadProfilesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A possibly empty list of Workload Profiles.
	//
	//
	WorkloadProfileResponses []shared.WorkloadProfileResponse
}
