// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDResourcesTypesRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDResourcesTypesResponse struct {
	ContentType string
	// Internal application error.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// A possibly empty list of Resources Types.
	//
	//
	ResourceTypeResponses []shared.ResourceTypeResponse
	StatusCode            int
	RawResponse           *http.Response
}
