// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDEnvsEnvIDRulesRuleIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Automation Rule ID.
	//
	//
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

type GetOrgsOrgIDAppsAppIDEnvsEnvIDRulesRuleIDResponse struct {
	// The AutomationRule
	//
	//
	AutomationRuleResponse *shared.AutomationRuleResponse
	ContentType            string
	StatusCode             int
	RawResponse            *http.Response
}
