// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDWorkloadProfilesProfileQidRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The fully qualified Workload ID. (If not a profile from the current org, must be prefixed with `{orgId}.` e.g. `humanitec.default-cronjob`)
	//
	//
	ProfileQid string `pathParam:"style=simple,explode=false,name=profileQid"`
}

type GetOrgsOrgIDWorkloadProfilesProfileQidResponse struct {
	ContentType string
	// The requested WorkloadProfile is not found.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// The requested WorkloadProfile.
	//
	//
	WorkloadProfileResponse *shared.WorkloadProfileResponse
}
