// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDResourcesDriversDriverIDRequest struct {
	// The Resource Driver ID.
	//
	//
	DriverID string `pathParam:"style=simple,explode=false,name=driverId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDResourcesDriversDriverIDResponse struct {
	ContentType string
	// The requested Resources Driver details.
	//
	//
	DriverDefinitionResponse *shared.DriverDefinitionResponse
	// A Resource Driver with the 'driverId' ID is not found or is not accessible by the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
