// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDEnvsEnvIDValueSetVersionsRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// (Optional) Return only value set version where the specified key changed
	//
	//
	KeyChanged *string `queryParam:"style=form,explode=true,name=key_changed"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDAppsAppIDEnvsEnvIDValueSetVersionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A possibly empty list of ValueSetVersion.
	//
	//
	ValueSetVersionResponses []shared.ValueSetVersionResponse
}
