// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDResourcesDefsDefIDRequest struct {
	// The Resource Definition ID.
	//
	//
	DefID string `pathParam:"style=simple,explode=false,name=defId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDResourcesDefsDefIDResponse struct {
	ContentType string
	// A Resource Definition with the 'defId' ID is not found.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// The requested Resources Definition details.
	//
	//
	ResourceDefinitionResponse *shared.ResourceDefinitionResponse
	StatusCode                 int
	RawResponse                *http.Response
}
