// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDEnvTypesEnvTypeIDRequest struct {
	// ID of the Environment Type.
	//
	//
	EnvTypeID string `pathParam:"style=simple,explode=false,name=envTypeId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDEnvTypesEnvTypeIDResponse struct {
	ContentType string
	// The Environment Type requested.
	//
	//
	EnvironmentTypeResponse *shared.EnvironmentTypeResponse
	// No Environment Type with `id` in Organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
