// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDEnvsEnvIDDeploysDeployIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Deployment ID.
	//
	//
	DeployID string `pathParam:"style=simple,explode=false,name=deployId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDAppsAppIDEnvsEnvIDDeploysDeployIDResponse struct {
	ContentType string
	// The Deployment requested.
	//
	//
	DeploymentResponse *shared.DeploymentResponse
	// No Deployment with `deployId` in Application and Environment.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
