// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDImagesImageIDRequest struct {
	// The Image ID.
	//
	//
	ImageID string `pathParam:"style=simple,explode=false,name=imageId"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDImagesImageIDResponse struct {
	ContentType string
	// No Image with an ID of `imageId` found within the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// The Image Object requested.
	//
	//
	ImageResponse *shared.ImageResponse
	StatusCode    int
	RawResponse   *http.Response
}
