// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDArtefactVersionsArtefactVersionIDRequest struct {
	// The Artefact Version ID.
	//
	//
	ArtefactVersionID string `pathParam:"style=simple,explode=false,name=artefactVersionId"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDArtefactVersionsArtefactVersionIDResponse struct {
	// An Artefact Version.
	//
	//
	ArtefactVersionResponse *shared.ArtefactVersionResponse
	ContentType             string
	// Malformed Artefact Version ID.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
