// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDResourcesDefsRequest struct {
	// (Optional) Filter Resource Definitions that may match a specific Application.
	//
	//
	App *string `queryParam:"style=form,explode=true,name=app"`
	// (Optional) Filter Resource Definitions that may match a specific Environment.
	//
	//
	Env *string `queryParam:"style=form,explode=true,name=env"`
	// (Optional) Filter Resource Definitions that may match a specific Environment Type.
	//
	//
	EnvType *string `queryParam:"style=form,explode=true,name=env_type"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// (Optional) Filter Resource Definitions that may match a specific Resource.
	//
	//
	Res *string `queryParam:"style=form,explode=true,name=res"`
	// (Optional) Filter Resource Definitions that may match a specific Resource Type.
	//
	//
	ResType *string `queryParam:"style=form,explode=true,name=res_type"`
}

type GetOrgsOrgIDResourcesDefsResponse struct {
	ContentType string
	// Internal application error.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// A possibly empty list of Resources Definitions.
	//
	//
	ResourceDefinitionResponses []shared.ResourceDefinitionResponse
	StatusCode                  int
	RawResponse                 *http.Response
}
