// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDArtefactVersionsRequest struct {
	// (Optional) Filter for non-archived Artefact Versions. If no filter is defined only non-archived Artefact Versions are returned, if the filter is true both archived and non-archived Versions are returned.
	//
	//
	Archived *string `queryParam:"style=form,explode=true,name=archived"`
	// (Optional) Filter Artefact Versions by name.
	//
	//
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// (Optional) Filter Artefact Versions by the reference to a Version of the same Artefact. This cannot be used together with `name`.
	//
	//
	Reference *string `queryParam:"style=form,explode=true,name=reference"`
}

type GetOrgsOrgIDArtefactVersionsResponse struct {
	// A list of Artefact Versions registered with your organization.
	//
	//
	ArtefactVersionResponses []shared.ArtefactVersionResponse
	ContentType              string
	// Bad request.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
