// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDEnvTypesRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDEnvTypesResponse struct {
	ContentType string
	// A list of Environment Types.
	//
	//
	EnvironmentTypeResponses []shared.EnvironmentTypeResponse
	StatusCode               int
	RawResponse              *http.Response
}
