// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDDeltasRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// If true, return archived Deltas.
	//
	//
	Archived *bool `queryParam:"style=form,explode=true,name=archived"`
	// Only return Deltas associated with the specified Environment.
	//
	//
	Env *string `queryParam:"style=form,explode=true,name=env"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDAppsAppIDDeltasResponse struct {
	ContentType string
	// A possibly empty list of Deployment Deltas.
	//
	//
	DeltaResponses []shared.DeltaResponse
	StatusCode     int
	RawResponse    *http.Response
}
