// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDImagesImageIDBuildsRequest struct {
	// The Image ID.
	//
	//
	ImageID string `pathParam:"style=simple,explode=false,name=imageId"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDImagesImageIDBuildsResponse struct {
	ContentType string
	// No Image with an ID of `imageId` found within the organization.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// Possibly empty list of Builds of Container Images.
	//
	//
	ImageBuildResponses []shared.ImageBuildResponse
	StatusCode          int
	RawResponse         *http.Response
}
