// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDArtefactsRequest struct {
	// (Optional) Filter Artefacts by name.
	//
	//
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// (Optional) Filter Artefacts by type.
	//
	//
	Type *string `queryParam:"style=form,explode=true,name=type"`
}

type GetOrgsOrgIDArtefactsResponse struct {
	// The list of Artefacts within the organization.
	//
	//
	ArtefactResponses []shared.ArtefactResponse
	ContentType       string
	StatusCode        int
	RawResponse       *http.Response
}
