// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDSetsSetIDDiffSourceSetIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// ID of the Deployment Set.
	//
	//
	SetID string `pathParam:"style=simple,explode=false,name=setId"`
	// ID of the Deployment Set to diff against.
	//
	//
	SourceSetID string `pathParam:"style=simple,explode=false,name=sourceSetId"`
}

type GetOrgsOrgIDAppsAppIDSetsSetIDDiffSourceSetIDResponse struct {
	ContentType string
	// A Deployment Delta which if applied to the Set with ID `sourceSetId` gives the Set with ID `setId`.
	//
	//
	PlainDeltaResponse *shared.PlainDeltaResponse
	StatusCode         int
	RawResponse        *http.Response
	// No Deployment Set with ID `setId` or `sourceSetId` found in Application.
	//
	//
	GetOrgsOrgIDAppsAppIDSetsSetIDDiffSourceSetID404ApplicationJSONString *string
}
