// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDEnvsEnvIDRuntimeRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDAppsAppIDEnvsEnvIDRuntimeResponse struct {
	ContentType string
	// Runtime info returned.
	//
	//
	RuntimeInfoResponse *shared.RuntimeInfoResponse
	StatusCode          int
	RawResponse         *http.Response
}
