// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDUsersRequest struct {
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDUsersResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A list of Users and the roles they hold.
	//
	//
	UserRoleResponses []shared.UserRoleResponse
}
