// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDRegistriesRequest struct {
	// Unique (alpha-numerical) organization identifier.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDRegistriesResponse struct {
	ContentType string
	// Request parameters are incomplete or invalid.
	//
	//
	ErrorInfoResponse *shared.ErrorInfoResponse
	// A Possibly empty list of Registries.
	//
	//
	RegistryResponses []shared.RegistryResponse
	StatusCode        int
	RawResponse       *http.Response
}
