// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDAppsAppIDWebhooksJobIDRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Webhook ID.
	//
	//
	JobID string `pathParam:"style=simple,explode=false,name=jobId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetOrgsOrgIDAppsAppIDWebhooksJobIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The requested webhook.
	//
	//
	WebhookResponse *shared.WebhookResponse
}
