// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetOrgsOrgIDArtefactsArtefactIDVersionsRequest struct {
	// (Optional) Filter for non-archived Artefact Versions. If no filter is defined only non-archived Artefact Versions are returned, if the filter is true both archived and non-archived Versions are returned.
	//
	//
	Archived *string `queryParam:"style=form,explode=true,name=archived"`
	// The Artefact ID.
	//
	//
	ArtefactID string `pathParam:"style=simple,explode=false,name=artefactId"`
	// (Optional) Limit the number of versions returned by the endpoint.
	//
	//
	Limit *string `queryParam:"style=form,explode=true,name=limit"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// (Optional) Filter Artefact Versions by by name including a version or digest.
	//
	//
	Reference *string `queryParam:"style=form,explode=true,name=reference"`
}

type GetOrgsOrgIDArtefactsArtefactIDVersionsResponse struct {
	// Returns all Versions of the specified Artefact.
	//
	//
	ArtefactVersionResponses []shared.ArtefactVersionResponse
	ContentType              string
	// Invalid inputs provided.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
