// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type GetSetsRequest struct {
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type GetSetsResponse struct {
	ContentType string
	// The Requested Deployment Set.
	//
	//
	SetResponses []shared.SetResponse
	StatusCode   int
	RawResponse  *http.Response
	// No Deployment Set with ID `setId` found in Application.
	//
	//
	GetSets404ApplicationJSONString *string
}
