// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetUsersMeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The extended user profile of the user.
	//
	//
	GetUsersMe200ApplicationJSONObject map[string]interface{}
}
