// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PatchOrgsOrgIDRegistriesRegIDRequest struct {
	// Record details to update.
	//
	//
	RegistryRequest shared.RegistryRequest `request:"mediaType=application/json"`
	// Unique (alpha-numerical) organization identifier.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// Unique (alpha-numerical) registry identifier.
	//
	//
	RegID string `pathParam:"style=simple,explode=false,name=regId"`
}

type PatchOrgsOrgIDRegistriesRegIDResponse struct {
	ContentType string
	// Request parameters or payload are incomplete or invalid.
	//
	//
	ErrorInfoResponse *shared.ErrorInfoResponse
	// Updated record details.
	//
	//
	RegistryResponse *shared.RegistryResponse
	StatusCode       int
	RawResponse      *http.Response
}
