// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PatchOrgsOrgIDResourcesDefsDefIDRequest struct {
	// The Resource Definition record details.
	//
	// The PATCH operation would change the value of the property if it is included in the request payload JSON, and not `null`. Missing and `null` properties are ignored.
	//
	// For the map properties, such as PatchResourceDefinitionRequest.DriverInputs, the merge operation is applied.
	//
	// Merge rules are as follows:
	//
	// - If a map property has a value, it is replaced (or added).
	//
	// - If a map property is set to `null`, it is removed.
	//
	// - If a map property is not included (missing in JSON), it remains unchanged.
	PatchResourceDefinitionRequestRequest shared.PatchResourceDefinitionRequestRequest `request:"mediaType=application/json"`
	// The Resource Definition ID.
	//
	//
	DefID string `pathParam:"style=simple,explode=false,name=defId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PatchOrgsOrgIDResourcesDefsDefIDResponse struct {
	ContentType string
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// The updated Resource Definition.
	//
	//
	ResourceDefinitionResponse *shared.ResourceDefinitionResponse
	StatusCode                 int
	RawResponse                *http.Response
}
