// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PatchOrgsOrgIDAppsAppIDEnvsEnvIDValuesKeyRequest struct {
	// At least `value` or `description` must be supplied. All other fields will be ignored.
	//
	//
	ValuePatchPayloadRequest shared.ValuePatchPayloadRequest `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The key to update.
	//
	//
	Key string `pathParam:"style=simple,explode=false,name=key"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PatchOrgsOrgIDAppsAppIDEnvsEnvIDValuesKeyResponse struct {
	ContentType string
	// Input not valid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// Shared Value successfully updated.
	//
	//
	ValueResponse *shared.ValueResponse
}
