// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDResourcesDriversRequest struct {
	// Resources Driver details.
	//
	//
	CreateDriverRequestRequest shared.CreateDriverRequestRequest `request:"mediaType=application/json"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDResourcesDriversResponse struct {
	ContentType string
	// The newly registered Resources Driver details.
	//
	//
	DriverDefinitionResponse *shared.DriverDefinitionResponse
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
