// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDWorkloadProfilesRequest struct {
	// Workload profile details.
	//
	//
	WorkloadProfileRequest shared.WorkloadProfileRequest `request:"mediaType=application/json"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDWorkloadProfilesResponse struct {
	ContentType string
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// The newly created Workload Profile.
	//
	//
	WorkloadProfileResponse *shared.WorkloadProfileResponse
}
