// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDEnvTypesRequest struct {
	// New Environment Type.
	//
	//
	EnvironmentTypeRequest shared.EnvironmentTypeRequest `request:"mediaType=application/json"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDEnvTypesResponse struct {
	ContentType string
	// The Environment Type requested.
	//
	//
	EnvironmentTypeResponse *shared.EnvironmentTypeResponse
	// The supplied `id` is not a valid ID or a required field is missing.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
