// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDResourcesAccountsRequest struct {
	CreateResourceAccountRequestRequest shared.CreateResourceAccountRequestRequest `request:"mediaType=application/json"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDResourcesAccountsResponse struct {
	ContentType string
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// The newly created Resources Account details.
	//
	//
	ResourceAccountResponse *shared.ResourceAccountResponse
	StatusCode              int
	RawResponse             *http.Response
}
