// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDImagesImageIDBuildsRequest struct {
	// The metadata associated with the build.
	//
	//
	ImageBuildRequest shared.ImageBuildRequest `request:"mediaType=application/json"`
	// The Image ID.
	//
	//
	ImageID string `pathParam:"style=simple,explode=false,name=imageId"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDImagesImageIDBuildsResponse struct {
	ContentType string
	// The supplied `imageId` is invalid or a required field is missing.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
