// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDAppsAppIDSetsSetIDRequest struct {
	// The Delta to apply to the Set.
	//
	// NOTE: The `id` parameter is ignored if provided. The request body should be the full Delta.
	DeltaRequest shared.DeltaRequest `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// ID of the Deployment Set.
	//
	//
	SetID string `pathParam:"style=simple,explode=false,name=setId"`
}

type PostOrgsOrgIDAppsAppIDSetsSetIDResponse struct {
	ContentType string
	// Deployment Delta is incompatible with the Deployment Set specified by `setId`.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// A Deployment Delta which if applied to the Set with ID `sourceSetId` gives the Set with ID `setId`.
	//
	//
	PostOrgsOrgIDAppsAppIDSetsSetID200ApplicationJSONString *string
	// No Deployment Set with ID `setId` found in Application.
	//
	//
	PostOrgsOrgIDAppsAppIDSetsSetID404ApplicationJSONString *string
}
