// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDAppsRequest struct {
	// The request ID, Human-friendly name and environment of the Application.
	//
	//
	ApplicationCreationRequest shared.ApplicationCreationRequest `request:"mediaType=application/json"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDAppsResponse struct {
	// The Application requested.
	//
	//
	ApplicationResponse *shared.ApplicationResponse
	ContentType         string
	// The request body was unparseable.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
