// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDRegistriesRequest struct {
	// A new record details.
	//
	//
	RegistryRequest shared.RegistryRequest `request:"mediaType=application/json"`
	// Unique (alpha-numerical) organization identifier.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDRegistriesResponse struct {
	ContentType string
	// Request parameters or payload are incomplete or invalid.
	//
	//
	ErrorInfoResponse *shared.ErrorInfoResponse
	// A newly created record details.
	//
	//
	RegistryResponse *shared.RegistryResponse
	StatusCode       int
	RawResponse      *http.Response
}
