// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDInvitationsRequest struct {
	// The email and the desired role
	//
	//
	UserInviteRequestRequest shared.UserInviteRequestRequest `request:"mediaType=application/json"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDInvitationsResponse struct {
	ContentType string
	// The request was invalid or the payload malformed.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// An temporary profile for the invited user.
	//
	//
	UserRoleResponses []shared.UserRoleResponse
}
