// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDAppsAppIDValueSetVersionsValueSetVersionIDRestoreKeyRequest struct {
	ValueSetActionPayloadRequest shared.ValueSetActionPayloadRequest `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Key of the value to be restored.
	//
	//
	Key string `pathParam:"style=simple,explode=false,name=key"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The ValueSetVersion ID.
	//
	//
	ValueSetVersionID string `pathParam:"style=simple,explode=false,name=valueSetVersionId"`
}

type PostOrgsOrgIDAppsAppIDValueSetVersionsValueSetVersionIDRestoreKeyResponse struct {
	ContentType string
	// Invalid request
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// The resulting ValueSetVersion
	//
	//
	ValueSetVersionResponse *shared.ValueSetVersionResponse
}
