// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDWorkloadProfilesProfileQidVersionsRequestBodyFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

// PostOrgsOrgIDWorkloadProfilesProfileQidVersionsRequestBody - Workload profile version metadata.
type PostOrgsOrgIDWorkloadProfilesProfileQidVersionsRequestBody struct {
	File *PostOrgsOrgIDWorkloadProfilesProfileQidVersionsRequestBodyFile `multipartForm:"file"`
	// Each Workload Profile has one or more Versions associated with it. In order to add a version, a Workload Profile must first be created.
	Metadata *shared.WorkloadProfileVersionRequest `multipartForm:"name=metadata,json"`
}

type PostOrgsOrgIDWorkloadProfilesProfileQidVersionsRequest struct {
	// Workload profile version metadata.
	//
	//
	RequestBody PostOrgsOrgIDWorkloadProfilesProfileQidVersionsRequestBody `request:"mediaType=multipart/form-data"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The Workload Profile ID.
	//
	//
	ProfileQid string `pathParam:"style=simple,explode=false,name=profileQid"`
}

type PostOrgsOrgIDWorkloadProfilesProfileQidVersionsResponse struct {
	ContentType string
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// The newly created Workload Profile Version metadata.
	//
	//
	WorkloadProfileVersionResponse *shared.WorkloadProfileVersionResponse
}
