// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDAppsAppIDEnvsRequest struct {
	// The ID, Name, Type, and Deployment the Environment will be derived from.
	//
	//
	EnvironmentDefinitionRequest shared.EnvironmentDefinitionRequest `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDAppsAppIDEnvsResponse struct {
	ContentType string
	// The new Environment.
	//
	//
	EnvironmentResponse *shared.EnvironmentResponse
	// The supplied `id` is an invalid ID or a required field is missing.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
