// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDAppsAppIDEnvsEnvIDDeploysRequest struct {
	// The Delta describing the change to the Environment and a comment.
	//
	//
	DeploymentRequest shared.DeploymentRequest `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PostOrgsOrgIDAppsAppIDEnvsEnvIDDeploysResponse struct {
	ContentType string
	// A description of the Deployment.
	//
	//
	DeploymentResponse *shared.DeploymentResponse
	// Error because the Delta is non-existent or incompatible with the state of the Environment.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
