// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDAppsAppIDValueSetVersionsValueSetVersionIDRestoreRequest struct {
	ValueSetActionPayloadRequest shared.ValueSetActionPayloadRequest `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// The ValueSetVersion ID.
	//
	//
	ValueSetVersionID string `pathParam:"style=simple,explode=false,name=valueSetVersionId"`
}

type PostOrgsOrgIDAppsAppIDValueSetVersionsValueSetVersionIDRestoreResponse struct {
	ContentType string
	// No ValueSetVersion with `valueSetVersionId` in App.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
	// The resulting ValueSetVersion
	//
	//
	ValueSetVersionResponse *shared.ValueSetVersionResponse
}
