// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PostOrgsOrgIDArtefactVersionsRequest struct {
	// The data needed to register a new Artefact Version within the organization.
	//
	//
	AddArtefactVersionPayloadRequest shared.AddArtefactVersionPayloadRequest `request:"mediaType=application/json"`
	// The organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// (Optional) Which version control system the version comes from. Default value is "git". If this parameter is not supplied or its value is "git", the provided ref, if not empty, is checked to ensure that it has the prefix "refs/".
	//
	//
	Vcs *string `queryParam:"style=form,explode=true,name=vcs"`
}

type PostOrgsOrgIDArtefactVersionsResponse struct {
	// An Artefact Version.
	//
	//
	ArtefactVersionResponse *shared.ArtefactVersionResponse
	ContentType             string
	// Either one or more request body parameters are missing or invalid, or the requested payload is not provided or malformed.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
