// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PutOrgsOrgIDResourcesDriversDriverIDRequest struct {
	UpdateDriverRequestRequest shared.UpdateDriverRequestRequest `request:"mediaType=application/json"`
	// The Resource Driver ID.
	//
	//
	DriverID string `pathParam:"style=simple,explode=false,name=driverId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PutOrgsOrgIDResourcesDriversDriverIDResponse struct {
	ContentType string
	// The updated Resources Driver details.
	//
	//
	DriverDefinitionResponse *shared.DriverDefinitionResponse
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	StatusCode             int
	RawResponse            *http.Response
}
