// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutOrgsOrgIDAppsAppIDEnvsEnvIDRuntimePausedRequest struct {
	// If the value is `true` the request is to pause an environment, if it is `false` is to resume an environment.
	//
	//
	RequestBody bool `request:"mediaType=application/json"`
	// The Application ID.
	//
	//
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// The Environment ID.
	//
	//
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PutOrgsOrgIDAppsAppIDEnvsEnvIDRuntimePausedResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
