// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"test-1/pkg/models/shared"
)

type PutOrgsOrgIDResourcesDefsDefIDRequest struct {
	// The Resource Definition record details.
	//
	// The PUT operation updates a resource definition using the provided payload. An empty driver_account or driver_inputs property will unset the existing values.
	//
	// Currently the resource and driver types can't be changed.
	UpdateResourceDefinitionRequestRequest shared.UpdateResourceDefinitionRequestRequest `request:"mediaType=application/json"`
	// The Resource Definition ID.
	//
	//
	DefID string `pathParam:"style=simple,explode=false,name=defId"`
	// The Organization ID.
	//
	//
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

type PutOrgsOrgIDResourcesDefsDefIDResponse struct {
	ContentType string
	// One or more request parameters is missing or invalid.
	//
	//
	HumanitecErrorResponse *shared.HumanitecErrorResponse
	// The updated Resource Definition.
	//
	//
	ResourceDefinitionResponse *shared.ResourceDefinitionResponse
	StatusCode                 int
	RawResponse                *http.Response
}
