// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AccountTypeResponse - Resource Account Types define cloud providers or protocols to which a resource account can belong.
type AccountTypeResponse struct {
	// Display Name.
	Name string `json:"name"`
	// Unique account type identifier (system-wide, across all organizations).
	Type string `json:"type"`
}
