// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AccountCredsRequest - AccountCreds represents an account credentials (either, username- or token-based).
type AccountCredsRequest struct {
	// Account credentials expiration timestamp.
	Expires *string `json:"expires,omitempty"`
	// Account password or token secret.
	Password string `json:"password"`
	// Security account login or token.
	Username string `json:"username"`
}
