// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ActiveResourceResponse - Active Resources represent the concrete resources provisioned for an Environment. They are provisioned on the first deployment after a dependency on a particular resource type is introduced into an Environment. In general, Active Resources are only deleted when their introductory Environment is deleted.
//
// Active Resources are provisioned based on a Resource Definition. The Resource Definition describes how to provision a concrete resource based on a Resource Type and metadata about the Environment (for example the Environment Type or the Application ID). The criteria for how to choose a Resource Definition is known as a Matching Criteria. If the Matching Criteria changes or the Resource Definition is deleted, the concrete resource represented by an Active Resource might be deleted and reprovisioned when a deployment occurs in the Environment.
type ActiveResourceResponse struct {
	// The ID of the App the resource is associated with.
	AppID string `json:"app_id"`
	// The Resource Definition that this resource was provisioned from.
	DefID string `json:"def_id"`
	// The deployment that the resource was last provisioned in.
	DeployID string `json:"deploy_id"`
	// The ID of the Environment the resource is associated with.
	EnvID string `json:"env_id"`
	// The Environment Type of the Environment specified by env_id.
	EnvType string `json:"env_type"`
	// the ID of the Organization the Active Resource is associated with.
	OrgID string `json:"org_id"`
	// The ID of the resource
	ResID string `json:"res_id"`
	// The data that the resource passes into the deployment ('values' only).
	Resource map[string]interface{} `json:"resource"`
	// Current resource status: 'pending', 'active', or 'deleting'.
	Status string `json:"status"`
	// The Resource Type of the resource
	Type string `json:"type"`
	// The time the resource was last provisioned as part of a deployment.
	UpdatedAt string `json:"updated_at"`
}
