// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApplicationCreationRequest - The request ID, Human-friendly name and environment of the Application.
type ApplicationCreationRequest struct {
	Env *EnvironmentBaseRequest `json:"env,omitempty"`
	// The ID which refers to a specific application.
	ID string `json:"id"`
	// The Human-friendly name for the Application.
	Name string `json:"name"`
}
