// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApplicationResponse - An Application is a collection of Workloads that work together. When deployed, all Workloads in an Application are deployed to the same namespace.
//
// Apps are the root of the configuration tree holding Environments, Deployments, Shared Values, and Secrets.
type ApplicationResponse struct {
	// The timestamp in UTC indicates when the Application was created.
	CreatedAt string `json:"created_at"`
	// The user who created the Application.
	CreatedBy string `json:"created_by"`
	// The Environments associated with the Application.
	Envs []EnvironmentBaseResponse `json:"envs"`
	// The ID which refers to a specific application.
	ID string `json:"id"`
	// The Human-friendly name for the Application.
	Name string `json:"name"`
}
