// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ArtefactVersionResponse - An Artefact Version represents a particular version of an Artefact that can be added to an Application.
type ArtefactVersionResponse struct {
	// If the Artefact Version is archived.
	Archived bool `json:"archived"`
	// The UUID of the Artefact.
	ArtefactID string `json:"artefact_id"`
	// (Optional) The commit ID the Artefact Version was built on.
	Commit string `json:"commit"`
	// The time when the Artefact Version was added to Humanitec.
	CreatedAt *string `json:"created_at,omitempty"`
	// The user ID of the user who added the Artefact Version to Humanitec.
	CreatedBy *string `json:"created_by,omitempty"`
	// (Optional) The Artefact Version digest.
	Digest string `json:"digest"`
	// The UUID of the Artefact Version.
	ID string `json:"id"`
	// The name of the Artefact.
	Name string `json:"name"`
	// (Optional) The ref the Artefact Version was built from.
	Ref string `json:"ref"`
	// The time when the Artefact Version was updated for the last time.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// The user ID of the user who performed the last updated on the Artefact Version.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// (Optional) The version of the Artefact Version.
	Version string `json:"version"`
}
