// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ArtefactResponse - Artefacts can be registered with Humanitec. Continuous Integration (CI) pipelines notify Humanitec when a new version of an Artefact becomes available. Humanitec tracks the Artefact along with metadata about how it was built.
type ArtefactResponse struct {
	// The time when the Artefact was added to Humanitec.
	CreatedAt *string `json:"created_at,omitempty"`
	// The user ID of the user who added the Artefact to Humanitec.
	CreatedBy *string `json:"created_by,omitempty"`
	// The UUID of the Artefact.
	ID string `json:"id"`
	// The name of the Artefact.
	Name string `json:"name"`
	// The type of the Artefact.
	Type string `json:"type"`
	// The time when the Artefact was updated for the last time.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// The user ID of the user who updated the Artefact for the last time.
	UpdatedBy *string `json:"updated_by,omitempty"`
}
