// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AutomationRuleResponse - An Automation Rule defining how and when artefacts in an environment should be updated.
type AutomationRuleResponse struct {
	// Whether the rule will be processed or not.
	Active bool `json:"active"`
	// A list of artefact names to be processed by the rule. If the array is empty, it implies include all. If `exclude_artefacts_filter` is true, this list describes the artefacts to exclude.
	ArtefactsFilter []string `json:"artefacts_filter"`
	// The timestamp in UTC of when the Automation Rule was created.
	CreatedAt string `json:"created_at"`
	// Whether the artefacts specified in `artefacts_filter` should be excluded (true) or included (false) in the automation rule.
	ExcludeArtefactsFilter bool `json:"exclude_artefacts_filter"`
	// DEPRECATED: Whether the images specified in `images_filter` should be excluded (true) or included (false) in the automation rule.
	ExcludeImagesFilter bool `json:"exclude_images_filter"`
	// The unique ID for this rule.
	ID string `json:"id"`
	// DEPRECATED: A list of image IDs to be processed by the rule. If the array is empty, it implies include all. If `exclude_images_filter` is true, this list describes images to exclude.
	ImagesFilter []string `json:"images_filter"`
	// DEPRECATED: A regular expression applied to the branch or tag name depending on the value of `update_to`. Defaults to match all if omitted or empty.
	Match string `json:"match"`
	// A regular expression applied to the ref of a new artefact version. Defaults to match all if omitted or empty.
	MatchRef string `json:"match_ref"`
	// Specifies the type of event. Currently, only updates to either branches or tags are supported. Must be `"update"`.
	Type string `json:"type"`
	// DEPRECATED: Specifies whether the update occurs on commit to branch or creation of tag. Must be one of `"branch"` or `"tag"`.
	UpdateTo string `json:"update_to"`
	// The timestamp in UTC of when the Automation Rule was updated.
	UpdatedAt string `json:"updated_at"`
}
