// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ClusterSecretRequest - ClusterSecret represents Kubernetes secret reference.
type ClusterSecretRequest struct {
	// Namespace to look for the Kubernetes secret definition in.
	Namespace string `json:"namespace"`
	// Name that identifies the Kubernetes secret.
	Secret string `json:"secret"`
}
