// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateResourceAccountRequestRequest - CreateResourceAccountRequest describes the request to create a new security account.
type CreateResourceAccountRequestRequest struct {
	// Credentials associated with the account.
	Credentials map[string]interface{} `json:"credentials,omitempty"`
	// Unique identifier for the account (in scope of the organization it belongs to).
	ID *string `json:"id,omitempty"`
	// Display name.
	Name *string `json:"name,omitempty"`
	// The type of the account
	Type *string `json:"type,omitempty"`
}
