// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateResourceDefinitionRequestRequest - CreateResourceDefinitionRequest describes a new ResourceDefinition request.
type CreateResourceDefinitionRequestRequest struct {
	// (Optional) The criteria to use when looking for a Resource Definition during the deployment.
	Criteria []MatchingCriteriaRequest `json:"criteria,omitempty"`
	// (Optional) Security account required by the driver.
	DriverAccount *string `json:"driver_account,omitempty"`
	// ValuesSecrets stores data that should be passed around split by sensitivity.
	DriverInputs *ValuesSecretsRequest `json:"driver_inputs,omitempty"`
	// The driver to be used to create the resource.
	DriverType string `json:"driver_type"`
	// The Resource Definition ID.
	ID string `json:"id"`
	// The display name.
	Name string `json:"name"`
	// The Resource Type.
	Type string `json:"type"`
}
