// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type DeltaMetadataRequest struct {
	Archived       *bool      `json:"archived,omitempty"`
	Contributers   []string   `json:"contributers,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	CreatedBy      *string    `json:"created_by,omitempty"`
	EnvID          *string    `json:"env_id,omitempty"`
	LastModifiedAt *time.Time `json:"last_modified_at,omitempty"`
	Name           *string    `json:"name,omitempty"`
	Shared         *bool      `json:"shared,omitempty"`
}
