// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeploymentErrorResponse - DeploymentError is an error happening during deployment
type DeploymentErrorResponse struct {
	Code      string `json:"code"`
	ErrorType string `json:"error_type"`
	Message   string `json:"message"`
	ObjectID  string `json:"object_id"`
	Scope     string `json:"scope"`
	Summary   string `json:"summary"`
}
