// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeploymentRequest - Deployments represent updates to the running state of an Environment.
//
// Deployments are made by applying _Deltas_ to a state defined by an existing Deployment. The Environment’s from_deploy property defines the Deployment. This Deployment is usually but not always in the current Environment. If the Deployment is from another Environment, the state of that Environment will be "cloned" into the current Environment with the option to apply a Delta.
type DeploymentRequest struct {
	// An optional comment to help communicate the purpose of the Deployment.
	Comment *string `json:"comment,omitempty"`
	// ID of the Deployment Delta describing the changes to the current Environment for this Deployment.
	DeltaID *string `json:"delta_id,omitempty"`
	// ID of the Value Set Version describe the values to be used for this Deployment.
	ValueSetVersionID *string `json:"value_set_version_id,omitempty"`
}
