// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DriverDefinitionResponse - DriverDefinition describes the resource driver.
//
// Resource Drivers are code that fulfils the Humanitec Resource Driver Interface. This interface allows for certain actions to be performed on resources such as creation and destruction. Humanitec provides numerous Resource Drivers “out of the box”. It is also possible to use 3rd party Resource Drivers or write your own.
type DriverDefinitionResponse struct {
	// List of resources accounts types supported by the driver
	AccountTypes []string `json:"account_types"`
	// The ID for this driver. Is used as `driver_type`.
	ID string `json:"id"`
	// A JSON Schema specifying the driver-specific input parameters.
	InputsSchema map[string]interface{} `json:"inputs_schema"`
	// Defines whether this driver is accessible to all Organizations.
	IsPublic bool `json:"is_public"`
	// The Organization this driver exists under. Useful as public drivers are accessible to other orgs.
	OrgID string `json:"org_id"`
	// The prefix where the driver resides or, if the driver is a virtual driver, the reference to an existing driver using the `driver://` schema of the format `driver://{orgId}/{driverId}`. Only members of the organization the driver belongs to can see `target`.
	Target *string `json:"target,omitempty"`
	// If the driver is a virtual driver, template defines a Go template that converts the driver inputs supplied in the resource definition into the driver inputs for the target driver.
	Template interface{} `json:"template,omitempty"`
	// The type of resource produced by this driver
	Type string `json:"type"`
}
