// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EnvironmentRuntimeInfoResponse - EnvironmentRuntimeInfo
type EnvironmentRuntimeInfoResponse struct {
	Error  *string `json:"error,omitempty"`
	ID     string  `json:"id"`
	Paused bool    `json:"paused"`
	Status *string `json:"status,omitempty"`
}
