// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EnvironmentResponse - Environments are independent spaces where Applications can run. An Application is always deployed into an Environment.
type EnvironmentResponse struct {
	// The timestamp in UTC of when the Environment was created.
	CreatedAt string `json:"created_at"`
	// The user who created the Environment
	CreatedBy string `json:"created_by"`
	// Deployments represent updates to the running state of an Environment.
	//
	// Deployments are made by applying _Deltas_ to a state defined by an existing Deployment. The Environment’s from_deploy property defines the Deployment. This Deployment is usually but not always in the current Environment. If the Deployment is from another Environment, the state of that Environment will be "cloned" into the current Environment with the option to apply a Delta.
	FromDeploy *DeploymentResponse `json:"from_deploy,omitempty"`
	// The ID the Environment is referenced as.
	ID string `json:"id"`
	// Deployments represent updates to the running state of an Environment.
	//
	// Deployments are made by applying _Deltas_ to a state defined by an existing Deployment. The Environment’s from_deploy property defines the Deployment. This Deployment is usually but not always in the current Environment. If the Deployment is from another Environment, the state of that Environment will be "cloned" into the current Environment with the option to apply a Delta.
	LastDeploy *DeploymentResponse `json:"last_deploy,omitempty"`
	// The Human-friendly name for the Environment.
	Name string `json:"name"`
	// The Environment Type. This is used for organizing and managing Environments.
	Type string `json:"type"`
}
