// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EnvironmentTypeResponse - Environment Types are a way of grouping and managing Environments. Every Environment has exactly 1 Environment Type.
//
// Environment Types can be used with External Resources to manage where resources such as databases are provisioned or even which cluster to deploy to.
type EnvironmentTypeResponse struct {
	// A Human-readable description of the Environment Type
	Description string `json:"description"`
	// The ID of the Environment Type. (Must be unique within an Organization.)
	ID string `json:"id"`
}
