// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EnvironmentDefinitionRequest - The ID, Name, Type, and Deployment the Environment will be derived from.
type EnvironmentDefinitionRequest struct {
	// Defines the existing Deployment the new Environment will be based on.
	FromDeployID string `json:"from_deploy_id"`
	// The ID the Environment is referenced as.
	ID string `json:"id"`
	// The Human-friendly name for the Environment.
	Name string `json:"name"`
	// The Environment Type. This is used for organizing and managing Environments.
	Type string `json:"type"`
}
