// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ErrorInfoResponse - ErrorInfo is returned by a handler in case of an error.
type ErrorInfoResponse struct {
	// An error details
	Error string `json:"error"`
}
