// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EventResponse - Events available for triggering automated jobs.
type EventResponse struct {
	// List of event properties which can be used as variables for this event
	Properties []string `json:"properties"`
	// Event scope
	Scope string `json:"scope"`
	// Event type
	Type string `json:"type"`
}
