// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EventBaseRequest - Properties which identify an event .
type EventBaseRequest struct {
	// Event scope
	Scope *string `json:"scope,omitempty"`
	// Event type
	Type *string `json:"type,omitempty"`
}
