// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EventBaseResponse - Properties which identify an event .
type EventBaseResponse struct {
	// Event scope
	Scope string `json:"scope"`
	// Event type
	Type string `json:"type"`
}
