// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// HumanitecErrorResponse - HumanitecError represents a standard Humanitec Error
type HumanitecErrorResponse struct {
	// (Optional) Additional information is enclosed here.
	Details map[string]interface{} `json:"details,omitempty"`
	// A short code to help with error identification.
	Error string `json:"error"`
	// A Human readable message about the error.
	Message string `json:"message"`
}
