// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ImageResponse - DEPRECATED: This type exists for historical compatibility and should not be used. Please use the [Artefact API](https://api-docs.humanitec.com/#tag/Artefact) instead.
//
// Container Images (known simply as Images) can be registered with Humanitec. Continuous Integration (CI) pipelines can then notify Humanitec when a new build of a Container Image becomes available. Humanitec tracks the Image along with metadata about how it was built.
type ImageResponse struct {
	// The time the first build of this Image was added to the organization
	AddedAt string `json:"added_at"`
	// A list of Image Builds ordered by addition date.
	Builds []ImageBuildResponse `json:"builds"`
	// The ID used to group different builds of the same Image together.
	ID string `json:"id"`
	// The Image Source that this Image is added via
	Source string `json:"source"`
}
