// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ImageBuildResponse - DEPRECATED: This type exists for historical compatibility and should not be used. Please use the [Artefact API](https://api-docs.humanitec.com/#tag/Artefact) instead.
//
// Holds the metadata associated withe a Container Image Build
type ImageBuildResponse struct {
	// The time when the build was added to Humanitec.
	AddedAt *string `json:"added_at,omitempty"`
	// The branch name of the branch the build was built on
	Branch string `json:"branch"`
	// The commit ID that this build was built from.
	Commit string `json:"commit"`
	// The fully qualified Image URL including registry, repository and tag.
	Image string `json:"image"`
	// The tag that the build was built from.
	Tags []string `json:"tags"`
}
