// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ImageBuildRequest - DEPRECATED: This type exists for historical compatibility and should not be used. Please use the [Artefact API](https://api-docs.humanitec.com/#tag/Artefact) instead.
//
// Holds the metadata associated withe a Container Image Build
type ImageBuildRequest struct {
	// The branch name of the branch the build was built on
	Branch *string `json:"branch,omitempty"`
	// The commit ID that this build was built from.
	Commit *string `json:"commit,omitempty"`
	// The fully qualified Image URL including registry, repository and tag.
	Image *string `json:"image,omitempty"`
	// The tag that the build was built from.
	Tags []string `json:"tags,omitempty"`
}
