// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JSONPatchResponse struct {
	Op    string      `json:"op"`
	Path  string      `json:"path"`
	Value interface{} `json:"value,omitempty"`
}
