// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MatchingCriteriaRuleRequest - MatchingCriteriaRule describes Matching Criteria rules.
type MatchingCriteriaRuleRequest struct {
	// (Optional) The ID of the Application that the Resources should belong to.
	AppID *string `json:"app_id,omitempty"`
	// (Optional) The ID of the Environment that the Resources should belong to. If `env_type` is also set, it must match the Type of the Environment for the Criteria to match.
	EnvID *string `json:"env_id,omitempty"`
	// (Optional) The Type of the Environment that the Resources should belong to. If `env_id` is also set, it must have an Environment Type that matches this parameter for the Criteria to match.
	EnvType *string `json:"env_type,omitempty"`
	// (Optional) The ID of the Resource in the Deployment Set. The ID is normally a `.` separated path to the definition in the set, e.g. `modules.my-module.externals.my-database`.
	ResID *string `json:"res_id,omitempty"`
}
