// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ModuleDeltasRequest - ModuleDeltas groups the different operations together.
type ModuleDeltasRequest struct {
	Add    map[string]map[string]ControllerRequest `json:"add,omitempty"`
	Remove []string                                `json:"remove,omitempty"`
	Update map[string][]UpdateActionRequest        `json:"update,omitempty"`
}
