// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ModuleDeltasResponse - ModuleDeltas groups the different operations together.
type ModuleDeltasResponse struct {
	Add    map[string]map[string]ControllerResponse `json:"add"`
	Remove []string                                 `json:"remove"`
	Update map[string][]UpdateActionResponse        `json:"update"`
}
