// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OrganizationResponse - An Organization is the top level object in Humanitec. All other objects belong to an Organization.
type OrganizationResponse struct {
	// Timestamp when the Organization was created.
	CreatedAt string `json:"created_at"`
	// User ID that created the Organization.
	CreatedBy string `json:"created_by"`
	// Unique ID for the Organization.
	ID string `json:"id"`
	// Human friendly name for the Organization.
	Name string `json:"name"`
}
