// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PatchResourceDefinitionRequestRequest - PatchResourceDefinitionRequest describes a ResourceDefinition change request.
type PatchResourceDefinitionRequestRequest struct {
	// (Optional) Security account required by the driver.
	DriverAccount *string `json:"driver_account,omitempty"`
	// ValuesSecrets stores data that should be passed around split by sensitivity.
	DriverInputs *ValuesSecretsRequest `json:"driver_inputs,omitempty"`
	// (Optional) Resource display name
	Name *string `json:"name,omitempty"`
}
