// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PlainDeltaResponse - Similar to the delta response, except the id and metadata properties.
//
// **Basic Structure**
//
// ```
//
//	{
//	  "modules" : {
//	    "add" : {
//	      <ID of Module to add to the Deployment Set> : {
//	        <An entire Modules object>
//	      }
//	    },
//	    "remove": [
//	      <An array of Module IDs that should be removed from the Deployment Set>
//	    ],
//	   "update": {
//	      <ID of Module already in the Set to be updated> : [
//	        <An array of JSON Patch (Search Results (RFC 6902) objects scoped to the module>
//	      ]
//	    }
//	  }
//	}
//
// ```
type PlainDeltaResponse struct {
	// ModuleDeltas groups the different operations together.
	Modules ModuleDeltasResponse   `json:"modules"`
	Shared  []UpdateActionResponse `json:"shared"`
}
