// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PodStateRequest - PodState represents single pod status
type PodStateRequest struct {
	ContainerStatuses []map[string]interface{} `json:"containerStatuses,omitempty"`
	Phase             *string                  `json:"phase,omitempty"`
	PodName           *string                  `json:"podName,omitempty"`
	Revision          *int64                   `json:"revision,omitempty"`
	Status            *string                  `json:"status,omitempty"`
}
