// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PodStateResponse - PodState represents single pod status
type PodStateResponse struct {
	ContainerStatuses []map[string]interface{} `json:"containerStatuses"`
	Phase             string                   `json:"phase"`
	PodName           string                   `json:"podName"`
	Revision          int64                    `json:"revision"`
	Status            string                   `json:"status"`
}
