// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RegistryCredsResponse - RegistryCreds represents current registry credentials (either, username- or token-based).
type RegistryCredsResponse struct {
	// Account credentials expiration timestamp.
	Expires *string `json:"expires,omitempty"`
	// Account password or token secret.
	Password string `json:"password"`
	// Registry name, usually in a "{domain}" or "{domain}/{project}" format.
	Registry string `json:"registry"`
	// ClusterSecretsMap stores a list of Kuberenetes secret references for the target deployment clusters.
	Secrets map[string]ClusterSecretResponse `json:"secrets"`
	// Security account login or token.
	Username string `json:"username"`
}
