// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RegistryResponse - Humanitec can be used to manage registry credentials. The Registry object represents how to match credentials to a particular registry.
//
// Humanitec supports all Docker compatible registries as well as the custom authentication formats used by AWS Elastic Container Registry and Google Container Registry. It also supports the injection of a specific secret to be copied from an existing namespace in the cluster.
type RegistryResponse struct {
	// The timestamp of when this record was created.
	CreatedAt *string `json:"created_at,omitempty"`
	// The user who created this record.
	CreatedBy *string `json:"created_by,omitempty"`
	// Indicates if registry secrets and credentials should be exposed to CI agents.
	EnableCi bool `json:"enable_ci"`
	// Registry ID, unique within the Organization.
	ID string `json:"id"`
	// Registry name, usually in a "{domain}" or "{domain}/{project}" format.
	Registry string `json:"registry"`
	// ClusterSecretsMap stores a list of Kuberenetes secret references for the target deployment clusters.
	Secrets map[string]ClusterSecretResponse `json:"secrets,omitempty"`
	// Registry type, describes the registry authentication method, and defines the schema for the credentials.
	//
	// Supported values:
	//
	// - `public`
	//
	// - `basic`
	//
	// - `google_gcr`
	//
	// - `amazon_ecr`
	//
	// - `secret_ref`
	Type string `json:"type"`
}
