// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResourceDefinitionResponse - A Resource Definitions describes how and when a resource should be provisioned. It links a driver (the how) along with a Matching Criteria (the when) to a Resource Type. This allows Humanitec to invoke a particular driver for the required Resource Type in the context of a particular Application and Environment.
//
// The schema for the `driver_inputs` is defined by the `input_schema` property on the DriverDefinition identified by the `driver_type` property.
type ResourceDefinitionResponse struct {
	// The timestamp of when this record has been created.
	CreatedAt *string `json:"created_at,omitempty"`
	// The user who created this record.
	CreatedBy *string `json:"created_by,omitempty"`
	// (Optional) The criteria to use when looking for a Resource Definition during the deployment.
	Criteria []MatchingCriteriaResponse `json:"criteria,omitempty"`
	// (Optional) Security account required by the driver.
	DriverAccount *string `json:"driver_account,omitempty"`
	// ValuesSecrets stores data that should be passed around split by sensitivity.
	DriverInputs *ValuesSecretsResponse `json:"driver_inputs,omitempty"`
	// The driver to be used to create the resource.
	DriverType *string `json:"driver_type,omitempty"`
	// The Resource Definition ID.
	ID string `json:"id"`
	// Indicates this definition is a built-in one (provided by Humanitec).
	IsDefault *bool `json:"is_default,omitempty"`
	// Indicates if this record has been marked for deletion. The Resource Definition that has been marked for deletion cannot be used to provision new resources.
	IsDeleted *bool `json:"is_deleted,omitempty"`
	// The display name.
	Name string `json:"name"`
	// The Organization ID.
	OrgID string `json:"org_id"`
	// The Resource Type.
	Type string `json:"type"`
}
