// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResourceDefinitionChangeResponse - ResourceDefinitionChange describes the effects of a Resource Definition or Matching Criteria update/deletion.
type ResourceDefinitionChangeResponse struct {
	// The ID of the App the resource is associated with.
	AppID string `json:"app_id"`
	// The ID of the Environment the resource is associated with.
	EnvID string `json:"env_id"`
	// The Resource Definition that this resource was provisioned from.
	FromDef string `json:"from_def"`
	// The ID of the resource
	ResID string `json:"res_id"`
	// The Resource Definition that resource *will be* provisioned from if the change is applied.
	ToDef string `json:"to_def"`
}
