// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResourceTypeResponse - Resources Types define the technology that Applications can have dependencies on.
//
// Each Resource Type also defines a set of input parameters (`inputs_schema`), and a set of output data (`outputs_schema`). When provisioning a resource, these are treated as inputs and outputs respectively.
type ResourceTypeResponse struct {
	// Category name (used to group similar resources on the UI).
	Category string `json:"category"`
	// A JSON Schema specifying the type-specific parameters for the driver (input).
	InputsSchema map[string]interface{} `json:"inputs_schema"`
	// Display name.
	Name string `json:"name"`
	// A JSON Schema specifying the type-specific data passed to the deployment (output).
	OutputsSchema map[string]interface{} `json:"outputs_schema"`
	// Unique resource type identifier (system-wide, across all organizations).
	Type string `json:"type"`
}
