// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RoleRequest - Role defines the role that will be used in request
type RoleRequest struct {
	Role *string `json:"role,omitempty"`
}
