// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateActionRequest - A representation of the main object defined in JSON Patch specified in RFC 6902 from the IETF. The main differences are:
//
// * Only `add`, `remove` and `replace` are supported
//
// * `remove` can have have its scope of application applied in its `value`. e.g. `{"scope":"delta"}
type UpdateActionRequest struct {
	From  *string     `json:"from,omitempty"`
	Op    *string     `json:"op,omitempty"`
	Path  *string     `json:"path,omitempty"`
	Value interface{} `json:"value,omitempty"`
}
