// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateResourceDefinitionRequestRequest - UpdateResourceDefinitionRequest describes a ResourceDefinition change request.
type UpdateResourceDefinitionRequestRequest struct {
	// (Optional) Security account required by the driver.
	DriverAccount *string `json:"driver_account,omitempty"`
	// ValuesSecrets stores data that should be passed around split by sensitivity.
	DriverInputs *ValuesSecretsRequest `json:"driver_inputs,omitempty"`
	// The display name.
	Name string `json:"name"`
}
