// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateResourceAccountRequestRequest - UpdateResourceAccountRequest describes the request to update the security account details.
type UpdateResourceAccountRequestRequest struct {
	// Credentials associated with the account.
	Credentials map[string]interface{} `json:"credentials,omitempty"`
	// Display name.
	Name *string `json:"name,omitempty"`
}
