// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateArtefactVersionPayloadRequest - UpdateArtefactVersionPayload contains the `archived` field that should be set in the Artefact Version to update.
type UpdateArtefactVersionPayloadRequest struct {
	// The Value of the archived value.
	Archived bool `json:"archived"`
}
