// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserProfileExtendedRequest - UserProfileExtended holds the profile information of a user including properties only accessible to the user.
type UserProfileExtendedRequest struct {
	// The time the user was first registered with Humanitec
	CreatedAt *string `json:"created_at,omitempty"`
	// The email address of the user from the profile
	Email *string `json:"email,omitempty"`
	// The User ID for this user
	ID *string `json:"id,omitempty"`
	// The name the user goes by
	Name       *string                `json:"name,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Roles      map[string]string      `json:"roles,omitempty"`
	// The type of the account. Could be user, service or system
	Type *string `json:"type,omitempty"`
}
