// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserRoleResponse - UserRole holds the mapping of role to user for a particular object.
type UserRoleResponse struct {
	// The time the user was first registered with Humanitec
	CreatedAt string `json:"created_at"`
	// The email address of the user from the profile
	Email *string `json:"email,omitempty"`
	// The User ID for this user
	ID string `json:"id"`
	// The status of an invitation (If applicable)
	Invite *string `json:"invite,omitempty"`
	// The name the user goes by
	Name string `json:"name"`
	// The role that this user holds
	Role string `json:"role"`
	// The type of the account. Could be user, service or system
	Type string `json:"type"`
	// The user ID that hold the role
	User *string `json:"user,omitempty"`
}
