// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserRoleRequest - UserRole holds the mapping of role to user for a particular object.
type UserRoleRequest struct {
	// The time the user was first registered with Humanitec
	CreatedAt *string `json:"created_at,omitempty"`
	// The email address of the user from the profile
	Email *string `json:"email,omitempty"`
	// The User ID for this user
	ID *string `json:"id,omitempty"`
	// The status of an invitation (If applicable)
	Invite *string `json:"invite,omitempty"`
	// The name the user goes by
	Name *string `json:"name,omitempty"`
	// The role that this user holds
	Role *string `json:"role,omitempty"`
	// The type of the account. Could be user, service or system
	Type *string `json:"type,omitempty"`
	// The user ID that hold the role
	User *string `json:"user,omitempty"`
}
