// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserInviteResponse - UserInvite stores the invitation details.
type UserInviteResponse struct {
	// The timestamp this invitation was created.
	CreatedAt string `json:"created_at"`
	// The ID of the user who created this invitation.
	CreatedBy string `json:"created_by"`
	// The email address of the user from the profile.
	Email *string `json:"email,omitempty"`
	// The timestamp this invitation would expire.
	ExpiresAt string `json:"expires_at"`
	// The User ID for this user.
	UserID string `json:"user_id"`
}
