// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ValuePatchPayloadRequest - At least `value` or `description` must be supplied. All other fields will be ignored.
type ValuePatchPayloadRequest struct {
	Description *string `json:"description,omitempty"`
	Value       *string `json:"value,omitempty"`
}
