// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ValueEditPayloadRequest - Both `value` and `description` must be supplied. All other fields will be ignored.
type ValueEditPayloadRequest struct {
	Description string  `json:"description"`
	IsSecret    *bool   `json:"is_secret,omitempty"`
	Key         *string `json:"key,omitempty"`
	Value       string  `json:"value"`
}
