// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// ValueSetVersionResponse - A Value Set Version can be used as a track record of Shared Values changes, to restore a previous version of a Shared Value or Value Set, or to purge a Shared Value if it shouldn't be accessible anymore.
type ValueSetVersionResponse struct {
	Change                  []JSONPatchResponse      `json:"change"`
	Comment                 string                   `json:"comment"`
	CreatedAt               time.Time                `json:"created_at"`
	CreatedBy               string                   `json:"created_by"`
	ID                      string                   `json:"id"`
	ResultOf                ValueSetVersionResultOf  `json:"result_of"`
	SourceValueSetVersionID string                   `json:"source_value_set_version_id"`
	UpdatedAt               time.Time                `json:"updated_at"`
	Values                  map[string]ValueResponse `json:"values"`
}
