// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WebhookRequest - Webhook is a special type of a Job, it performs a HTTPS request to a specified URL with specified headers.
type WebhookRequest struct {
	// Defines whether this job is currently disabled.
	Disabled *bool                  `json:"disabled,omitempty"`
	Headers  map[string]interface{} `json:"headers,omitempty"`
	// Job ID, unique within the Organization
	ID      *string                `json:"id,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	// A list of Events by which the Job is triggered
	Triggers []EventBaseRequest `json:"triggers,omitempty"`
	// Thw webhook's URL (without protocol, only HTTPS is supported)
	URL *string `json:"url,omitempty"`
}
