// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// WorkloadProfileResponse - Workload Profiles provide the baseline configuration for Workloads in Applications in Humanitec. Developers can configure various features of a workload profile to suit their needs. Examples of features might be `schedules` used in Kubernetes CronJobs or `ingress` which might be used to expose Pods controlled by a Kubernetes Deployment.
//
// Workloads in Humanitec are implemented as Helm Charts which must implement a specific schema.
type WorkloadProfileResponse struct {
	// Creation date
	CreatedAt time.Time `json:"created_at"`
	// User created the profile
	CreatedBy string `json:"created_by"`
	// Workload Profile ID
	ID string `json:"id"`
	// The latest version of the profile
	Latest string `json:"latest"`
	// Organization ID
	OrgID string `json:"org_id"`
}
