// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkloadProfileVersionRequest - Each Workload Profile has one or more Versions associated with it. In order to add a version, a Workload Profile must first be created.
type WorkloadProfileVersionRequest struct {
	// A map of Features. If referencing built in Humanitec features, the fully qualified feature name must be used: e.g. `humanitec/annotations`.
	//
	// {
	//
	// }
	Features map[string]interface{} `json:"features,omitempty"`
	// Notes
	Notes *string `json:"notes,omitempty"`
}
